apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: broad-beaver-nodejs 
  janus-idp.io/tekton: broad-beaver-nodejs
  backstage.io/kubernetes-id: broad-beaver-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: broad-beaver-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  